### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by leejulee** [apolkingg8/JQueryDatePickerTW#1]
您好：剛好有使用到你的js，發現有個defaultDate的設定會與您原先的yearRange判別有衝突，個人修正方式如下，供您參考，謝謝。
if (twSettings.defaultDate === undefined && twSettings.yearRange && isFirstTime) {
                dateNative.setFullYear(twSettings.yearRange.split(':')[1]);
           }

**Comment by apolkingg8** [comment]
謝謝您的feedback，我會在近日fix它 :)

**Comment by apolkingg8** [comment]
fixed. 現在兩者可以並存了

**Comment by leejulee** [comment]
thanks
